### ISSUE TITLE
Missing values

### ISSUE THREAD

**Issue by david-i-berry** [wmo-im/wis2-data-analysis#6]
At 

https://github.com/wmo-im/wis2-data-analysis/blob/6ab81446b5cd5a5bb4239d6368bf0f5497742d6f/data_processor.py#L45C65-L45C65

check for missing values using something like:

https://github.com/wmo-im/bufr2geojson/blob/dcf9bbf1aca6b287179d31805727bb28da609f2d/bufr2geojson/__init__.py#L674C20-L674C20

**Comment by celgarrai** [comment]
done
